class data_class {
  static List ans = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20"
  ];
  static List hint = [
    "Sum",
    "Multipulication",
    "6*5 = 30",
    "Count the Square",
    "Try Multipulication",
    "Look at the different of two number",
    "Apply BOOMAS",
    "Splite 21 into 2 and 1",
    "4 = 2*2",
    "Diagonal Sum0",
  ];
  static List share_lvl =[
    "myasset/image/share1.png",
    "myasset/image/share2.png",
    "myasset/image/share3.png",
    "myasset/image/share4.png",
    "myasset/image/share5.png",
    "myasset/image/share6.png",
    "myasset/image/share7.png",
    "myasset/image/share8.png",
    "myasset/image/share9.png",
    "myasset/image/share10.png",
    "myasset/image/share11.png",
    "myasset/image/share12.png",
    "myasset/image/share13.png",
    "myasset/image/share14.png",
    "myasset/image/share15.png",
    "myasset/image/share16.png",
    "myasset/image/share17.png",
    "myasset/image/share18.png",
    "myasset/image/share19.png",
    "myasset/image/share20.png",
  ];
  static List lvl = [
    "myasset/image/p1.png",
    "myasset/image/p2.png",
    "myasset/image/p3.png",
    "myasset/image/p4.png",
    "myasset/image/p5.png",
    "myasset/image/p6.png",
    "myasset/image/p7.png",
    "myasset/image/p8.png",
    "myasset/image/p9.png",
    "myasset/image/p10.png",
    "myasset/image/p11.png",
    "myasset/image/p12.png",
    "myasset/image/p13.png",
    "myasset/image/p14.png",
    "myasset/image/p15.png",
    "myasset/image/p16.png",
    "myasset/image/p17.png",
    "myasset/image/p18.png",
    "myasset/image/p19.png",
    "myasset/image/p20.png",
  ];
  static List lock = [
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
    "myasset/image/lock.png",
  ];
}
